#!/bin/bash

set -euo pipefail

# ANSI color codes and emoji for readability
GREEN=$(tput setaf 2)   # 🟢
YELLOW=$(tput setaf 3)  # 🟡
RESET=$(tput sgr0)      # 🔄

# Function to display loading animation
function loading_animation() {
    local pid=$!
    local delay=0.15
    local spin='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'

    while ps -p $pid >/dev/null; do
        local temp=${spin#?}
        printf " [%c] " "$spin"
        local spin=$temp${spin%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done

    printf "    \b\b\b\b"
}

echo -n "${GREEN} 🟢 Starting user setup...${RESET}"
sleep 1
echo -ne "\r${GREEN} ✅ Starting user setup...${RESET}"
sleep 1
echo -ne "\r${GREEN} 🟢 Starting user setup...${RESET}"
sleep 1
echo -e "\r${GREEN} ✅ Starting user setup...${RESET}"


printf "${GREEN}🌟 Starting user setup...${RESET}\n"

read -p "${YELLOW}🔑 Enter login: ${RESET}" login
read -p "${YELLOW}🔒 Enter password: ${RESET}" -s password
read -p "${YELLOW}🔑 Enter path of SSH public key: ${RESET}" -e ssh_pub_path

printf "${GREEN}🚀 Creating user directories and setting up SSH...${RESET}\n"

homedir="/home/$login"
ssh_dir="$homedir/.ssh"

sudo mkdir -p "$ssh_dir"
sudo cat "$ssh_pub_path" >> "$ssh_dir/authorized_keys"
sudo cp -rT /etc/skel "$homedir"
sudo useradd -d "$homedir" -s /bin/bash "$login"
sudo chown -R "$login:$login" "$homedir"
echo "$login:$password" | sudo chpasswd

printf "${GREEN}✅ User setup completed successfully!${RESET}\n"

# Check if user is successfully added
grep "$login" /etc/passwd

printf "${GREEN}🎉 Enjoy your new user account!${RESET}\n"

